# Configuration file 

input_tsv: "facebook.csv"    # input file name
output_dir: "Facebook"       # output directory
k: 10                        # Select Landmark budget (2, 5, 10, 20, 50, 100, 500)
h_min: 1                     # hop exclusion (0 or 1)
lm_sel: "brandes"             # Select Landmark Startegy (random, degree, degree_h, closeness, closeness_h, brandes, brandes_h)
closeness_samples: 200       # Sample size for closeness/closeness_h
queries:                     # distance queries (Give original Node ID from the input file or generate quires using generate_queries.py)
- [69, 17616]
- [93, 17616]
- [6335, 17616]
- [151, 17616]
- [11, 17616]
- [7618, 17616]
- [17163, 17616]
- [10945, 17616]
- [2449, 17616]
- [14027, 17616]
- [4003, 17324]
- [17363, 17616]
- [17616, 18689]
- [725, 17324]
- [116, 17616]
- [15746, 17180]
- [15174, 17616]
- [1443, 17616]
- [53, 17616]
- [11817, 17616]
- [17616, 22435]
- [3279, 17616]
- [3269, 17324]
- [17253, 17616]
- [10152, 17616]
- [17616, 20207]
- [5066, 17616]
- [17616, 18727]
- [17616, 18886]
- [10974, 17616]
- [17180, 21101]
- [3816, 17616]
- [2416, 17616]
- [12027, 17616]
- [17616, 20895]
- [2280, 17616]
- [16260, 17616]
- [1366, 17324]
- [16071, 17616]
- [2629, 17616]
- [7488, 17616]
- [17324, 21729]
- [17616, 18893]
- [6521, 17324]
- [4139, 14846]
- [15121, 17616]
- [128, 17616]
- [17616, 20071]
- [9001, 17616]
- [4948, 17616]
- [17616, 17765]
- [3223, 17616]
- [602, 17616]
- [15368, 17616]
- [5307, 17616]
- [2, 17616]
- [17616, 19493]
- [10895, 17616]
- [17616, 18024]
- [89, 17616]
- [11743, 17324]
- [366, 17616]
- [6709, 17616]
- [12, 17616]
- [126, 17616]
- [4228, 14846]
- [17616, 17845]
- [14381, 17616]
- [15750, 17324]
- [17616, 18153]
- [13678, 17324]
- [8258, 17324]
- [17324, 20254]
- [10857, 17616]
- [152, 17616]
- [3479, 17616]
- [7595, 17616]
- [9695, 17616]
- [1407, 14846]
- [17616, 20510]
- [4246, 17616]
- [467, 17616]
- [17324, 19799]
- [4064, 17616]
- [17500, 17616]
- [233, 17616]
- [11742, 14846]
- [8149, 17616]
- [16524, 17616]
- [2509, 17616]
- [125, 17616]
- [139, 17616]
- [17324, 22086]
- [8396, 17616]
- [8004, 17616]
- [9910, 14846]
- [15868, 17616]
- [10469, 17616]
- [15172, 17616]
- [14111, 17616]
- [5826, 17616]
- [17616, 22261]
- [971, 17616]
- [8096, 14846]
- [916, 17616]
- [17616, 21538]
- [17357, 17616]
- [17616, 19337]
- [7216, 17616]
- [11878, 17616]
- [2991, 17324]
- [290, 17616]
- [15213, 17616]
- [1193, 17616]
- [5719, 17616]
- [16993, 17180]
- [9382, 14846]
- [14155, 17616]
- [9677, 17616]
- [12972, 17616]
- [8827, 17616]
- [1209, 17616]
- [17616, 21755]
- [14241, 17616]
- [4476, 17616]
- [174, 17616]
- [15129, 17616]
- [4320, 17616]
- [1626, 17616]
- [14778, 17324]
- [10166, 17616]
- [14467, 17616]
- [17616, 19753]
- [23, 17616]
- [3987, 14846]
- [14186, 17324]
- [347, 17616]
- [17616, 19495]
- [17616, 21323]
- [17616, 21809]
- [7632, 14846]
- [16742, 17616]
- [4987, 17616]
- [5035, 17616]
- [17080, 17616]
- [170, 17616]
- [8341, 17180]
- [5538, 17616]
- [3400, 14846]
- [27, 17616]
- [1, 17616]
- [6230, 17616]
- [2595, 17324]
- [7139, 17616]
- [327, 14846]
- [16754, 17616]
- [16026, 17616]
- [353, 17616]
- [22, 17616]
- [11354, 17180]
- [3975, 17616]
- [10126, 17616]
- [8265, 14846]
- [6823, 17616]
- [11046, 17324]
- [15735, 17616]
- [17324, 19342]
- [10539, 17616]
- [1837, 17180]
- [12845, 17616]
- [17324, 17502]
- [17616, 21955]
- [481, 17616]
- [17324, 18124]
- [6115, 17324]
- [6390, 17616]
- [961, 17616]
- [12348, 14846]
- [7104, 17616]
- [4808, 17616]
- [626, 17616]
- [6566, 17616]
- [1200, 17616]
- [6829, 17616]
- [589, 17616]
- [17616, 20594]
- [4253, 17616]
- [8232, 17616]
- [14701, 17616]
- [7499, 17616]
- [13153, 17324]
- [959, 17616]
- [7, 17616]
- [555, 17616]
- [17130, 17616]
- [7552, 17616]
- [17324, 20008]
- [17324, 18724]
- [7106, 17616]
- [14332, 17616]
- [7694, 17616]
- [14792, 17616]
- [14325, 17616]
- [17616, 21708]
- [8498, 17616]
- [13966, 17616]
- [7164, 17616]
- [33, 17616]
- [14944, 17616]
- [2224, 17616]
- [17616, 17866]
- [13511, 17616]
- [59, 17616]
- [12823, 17324]
- [17616, 21280]
- [10632, 17616]
- [14249, 17616]
- [17616, 21157]
- [8139, 17616]
- [10095, 17616]
- [17616, 19026]
- [16733, 17616]
- [1156, 17616]
- [17616, 21059]
- [9048, 17616]
- [9600, 17616]
- [5046, 17616]
- [11209, 17616]
- [17616, 21301]
- [1041, 17616]
- [161, 17616]
- [12830, 17616]
- [17616, 20135]
- [11332, 17324]
- [17616, 22177]
- [17616, 20107]
- [9905, 17616]
- [8106, 17616]
- [17616, 20269]
- [8403, 17180]
- [3443, 17616]
- [16688, 17616]
- [17255, 17616]
- [17324, 19234]
- [9151, 17616]
- [8533, 17616]
- [15555, 17180]
- [672, 17616]
- [12145, 17616]
- [6946, 17616]
- [8734, 17616]
- [17616, 19023]
- [3305, 17616]
- [15867, 17616]
- [17616, 21366]
- [17616, 21247]
- [10843, 17616]
- [10611, 17616]
- [5686, 17324]
- [7571, 17616]
- [8239, 17616]
- [6615, 17324]
- [1101, 17616]
- [17324, 21551]
- [3781, 17616]
- [7502, 17616]
- [14862, 17616]
- [14164, 17616]
- [2904, 17616]
- [213, 17616]
- [11315, 17616]
- [12601, 17616]
- [4677, 17616]
- [17616, 21768]
- [16, 17616]
- [17616, 19643]
- [14080, 17616]
- [71, 17616]
- [17616, 20188]
- [4000, 17616]
- [17370, 17616]
- [7431, 17616]
- [10904, 17616]
- [7781, 17616]
- [17616, 19540]
- [12169, 17616]
- [17324, 19128]
- [17433, 17616]
- [17324, 19757]
- [3766, 17616]
- [17616, 19729]
- [13602, 17616]
- [15732, 17324]
- [13128, 17324]
- [17616, 22208]
- [13798, 17616]
- [17616, 17635]
- [16161, 17180]
- [3238, 17616]
- [4502, 17616]
- [13197, 17616]
- [17616, 18216]
- [16151, 17324]
- [17324, 17772]
- [16490, 17324]
- [5951, 17616]
- [17616, 22020]
- [1679, 17616]
- [9990, 17616]
- [8, 17616]
- [9415, 17616]
- [17178, 17616]
- [17, 17616]
- [4, 17616]
- [17616, 20316]
- [9021, 17616]
- [828, 17616]
- [9574, 17616]
- [2157, 17616]
- [12062, 17616]
- [9946, 17616]
- [17346, 17616]
- [13025, 17324]
- [14409, 17616]
- [3798, 17616]
- [16972, 17616]
- [6857, 17180]
- [194, 17616]
- [17242, 17616]
- [15, 17616]
- [17616, 20938]
- [6037, 17616]
- [16561, 17616]
- [14521, 17616]
- [172, 17616]
- [10481, 17616]
- [18, 17616]
- [1840, 17616]
- [4328, 17616]
- [8514, 17616]
- [12902, 17616]
- [4563, 17616]
- [395, 17616]
- [4794, 17616]
- [17616, 22405]
- [17324, 22338]
- [11460, 17616]
- [17616, 18152]
- [6686, 17616]
- [14846, 15718]
- [14575, 17616]
- [12458, 17616]
- [146, 17616]
- [17324, 19352]
- [6457, 17616]
- [17616, 20092]
- [12807, 17616]
- [17616, 21888]
- [11310, 17616]
- [17616, 19677]
- [17616, 22282]
- [17616, 21787]
- [1377, 17616]
- [4547, 17324]
- [2153, 17616]
- [17212, 17616]
- [4048, 17616]
- [1766, 17616]
- [15940, 17616]
- [17616, 22304]
- [17616, 21035]
- [11102, 17616]
- [17616, 21307]
- [17324, 19743]
- [2597, 17180]
- [16994, 17616]
- [17616, 19129]
- [12091, 14846]
- [17616, 20937]
- [7144, 17324]
- [17616, 18059]
- [6540, 17616]
- [142, 17616]
- [17616, 18062]
- [701, 17616]
- [1658, 17616]
- [2434, 17324]
- [17324, 20896]
- [15507, 17616]
- [17616, 20276]
- [17616, 17624]
- [3212, 17616]
- [945, 17616]
- [4172, 17616]
- [14628, 17616]
- [17616, 21527]
- [8002, 17616]
- [15103, 17616]
- [10088, 17616]
- [17324, 20846]
- [13, 17616]
- [14846, 18449]
- [6173, 17616]
- [17616, 19031]
- [9, 17616]
- [17324, 20345]
- [34, 17616]
- [2773, 17616]
- [2689, 17616]
- [17616, 19957]
- [4683, 17616]
- [15531, 17616]
- [17588, 17616]
- [5857, 17616]
- [7184, 17616]
- [13716, 17616]
- [10134, 17616]
- [14772, 17616]
- [16915, 17180]
- [16332, 17180]
- [1997, 17616]
- [68, 17616]
- [7863, 17324]
- [11718, 17616]
- [63, 17616]
- [7206, 17616]
- [86, 17616]
- [14179, 17616]
- [15774, 17616]
- [3192, 17616]
- [3496, 17324]
- [11103, 17324]
- [17616, 21774]
- [13616, 17616]
- [4738, 17616]
- [17325, 17616]
- [11034, 17616]
- [6333, 17616]
- [8843, 17616]
- [8439, 17616]
- [17616, 19635]
- [12715, 17616]
- [11655, 17616]
- [16895, 17616]
- [1189, 17616]
- [1211, 17616]
- [17324, 21506]
- [10426, 17616]
- [4887, 17616]
- [115, 17616]
- [17616, 19016]
- [17324, 20627]
- [7966, 17616]
- [119, 17616]
- [11971, 17616]
- [4323, 17616]
- [10622, 17616]
- [0, 17616]
- [14392, 17616]
- [7212, 17616]
- [1063, 17616]
- [12305, 17616]
- [783, 17616]
- [1861, 17324]
- [11816, 17616]
- [1853, 17324]
- [16128, 17616]
- [17616, 18374]
- [15649, 17616]
- [16303, 17616]
- [17616, 18497]
- [2833, 17616]
- [1744, 17616]
- [24, 17616]
- [13205, 17616]
- [17038, 17616]
- [17180, 21203]
- [1710, 17616]
- [12912, 17324]
- [6219, 17616]
- [526, 17616]
- [293, 17616]
- [4670, 17616]
- [16406, 17616]
- [3576, 17616]
- [17616, 20012]
- [12401, 17616]
- [2812, 17616]
- [17616, 21102]
- [11345, 17616]
- [17616, 21963]
- [17254, 17324]
- [11332, 17616]
- [16502, 17616]
- [8952, 14846]
- [15718, 17616]
- [5990, 17180]
- [14936, 17324]
- [12872, 17616]
- [17616, 19020]