# lm selection - random, degree, closeness, degree_h,  

input_tsv: "large_twitch_edges.csv"
output_dir: "output"
k: 5
h_min: 1
lm_sel: "degree_h"
queries:
- ['16210', '45476']
- ['124223', '58647']
- ['133892', '164326']
- ['24551', '46707']
- ['12589', '87037']
- ['112948', '76539']
- ['18468', '87750']
- ['12624', '17153']
- ['120948', '36136']
- ['109268', '65398']
- ['4833', '76418']
- ['126762', '155701']
- ['12624', '146403']
- ['100371', '67810']
- ['164483', '55087']
- ['117109', '164191']
- ['124563', '153712']
- ['12624', '98085']
- ['135633', '91575']
- ['138939', '1395']
- ['134468', '24174']
- ['116714', '154757']
- ['144474', '17088']
- ['57164', '8256']
- ['12624', '54078']
- ['13617', '64982']
- ['153213', '2221']
- ['114366', '128209']
- ['39902', '93933']
- ['143346', '166160']
- ['41520', '68639']
- ['118367', '12589']
- ['27700', '3811']
- ['116570', '59759']
- ['12624', '129607']
- ['107913', '157210']
- ['12624', '136611']
- ['110931', '144474']
- ['133021', '55087']
- ['109378', '74727']
- ['52370', '65851']
- ['123098', '62991']
- ['47387', '8149']
- ['100351', '11005']
- ['3791', '57164']
- ['38478', '73503']
- ['107394', '60193']
- ['125652', '144474']
- ['71465', '82644']
- ['131774', '146052']
- ['152789', '88597']
- ['39076', '98462']
- ['38478', '73040']
- ['165529', '36729']
- ['134866', '91601']
- ['153213', '75193']
- ['100432', '142999']
- ['2979', '53330']
- ['102423', '142075']
- ['26058', '59325']
- ['106661', '68214']
- ['141207', '15448']
- ['144186', '85352']
- ['121496', '15128']
- ['23571', '91575']
- ['104402', '157052']
- ['143346', '144458']
- ['34903', '64042']
- ['19940', '20818']
- ['135973', '93933']
- ['44461', '66452']
- ['106712', '15581']
- ['165854', '94585']
- ['153213', '46761']
- ['118767', '74727']
- ['130061', '98582']
- ['40232', '97696']
- ['22336', '7206']
- ['120045', '144474']
- ['114991', '149281']
- ['27708', '76701']
- ['160187', '6229']
- ['100700', '71465']
- ['130462', '135824']
- ['12273', '71465']
- ['70444', '98462']
- ['16056', '17596']
- ['164326', '40357']
- ['109410', '162838']
- ['133628', '164358']
- ['5292', '8628']
- ['150065', '33421']
- ['160733', '92125']
- ['12624', '81399']
- ['145383', '846']
- ['87016', '88291']
- ['134989', '156640']
- ['147585', '78547']
- ['51108', '59759']
- ['161159', '83768']
- ['135172', '24298']
- ['103086', '133628']
- ['133165', '156512']
- ['132229', '93933']
- ['102147', '36729']
- ['139059', '75699']
- ['106439', '57164']
- ['144474', '53744']
- ['90403', '93301']
- ['166880', '91614']
- ['84485', '98462']
- ['153256', '36136']
- ['116980', '93933']
- ['4352', '60193']
- ['161889', '44743']
- ['59551', '68322']
- ['100115', '894']
- ['49945', '8149']
- ['100115', '159983']
- ['119228', '959']
- ['141790', '4833']
- ['159866', '166995']
- ['100764', '75202']
- ['133628', '36560']
- ['35889', '76810']
- ['109665', '133628']
- ['117109', '141055']
- ['18521', '6229']
- ['35756', '65825']
- ['32703', '35858']
- ['120534', '98462']
- ['76774', '87249']
- ['13617', '150954']
- ['127618', '35756']
- ['152587', '91575']
- ['135824', '137655']
- ['163653', '83426']
- ['12624', '58891']
- ['126762', '134705']
- ['113117', '146052']
- ['121158', '18588']
- ['121859', '54740']
- ['157273', '163233']
- ['133342', '57164']
- ['27808', '36136']
- ['112948', '118593']
- ['145909', '67609']
- ['133628', '16515']
- ['13024', '133628']
- ['73604', '82382']
- ['117421', '142075']
- ['48734', '87772']
- ['124301', '91575']
- ['112344', '164326']
- ['102587', '7206']
- ['105024', '121657']
- ['133165', '159536']
- ['133628', '52414']
- ['133628', '149474']
- ['33353', '9053']
- ['2582', '82523']
- ['21852', '78174']
- ['57164', '93994']
- ['129084', '133628']
- ['144050', '55958']
- ['17596', '9067']
- ['121300', '83858']
- ['100675', '7206']
- ['102265', '52132']
- ['101184', '46011']
- ['129488', '167269']
- ['166995', '32624']
- ['105457', '154286']
- ['151065', '85738']
- ['51315', '91575']
- ['114366', '125517']
- ['106038', '93933']
- ['132522', '143346']
- ['60193', '79893']
- ['13617', '43366']
- ['137198', '85604']
- ['2886', '60908']
- ['141637', '7214']
- ['129951', '62991']
- ['54360', '96576']
- ['113862', '152282']
- ['162066', '25643']
- ['116714', '126192']
- ['226', '3964']
- ['70539', '92508']
- ['37482', '93933']
- ['144762', '74924']
- ['133020', '167697']
- ['137813', '143346']
- ['146052', '8815']
- ['102265', '154212']
- ['12624', '54931']
- ['102864', '93933']
- ['117935', '35889']
- ['166995', '97710']
- ['57164', '65409']
- ['146052', '4836']
- ['14527', '16208']
- ['13617', '43811']
- ['135408', '5179']
- ['102606', '71465']
- ['145279', '44677']
- ['90169', '95793']
- ['154655', '39891']
- ['133628', '33266']
- ['133628', '78624']
- ['35889', '90601']
- ['103580', '152160']
- ['12624', '24131']
- ['10853', '113425']
- ['135008', '91575']
- ['133628', '150282']
- ['15532', '25643']
- ['76636', '99126']
- ['8149', '9500']
- ['17596', '76615']
- ['86386', '98462']
- ['42562', '59294']
- ['153282', '160375']
- ['36136', '74858']
- ['100089', '32303']
- ['153213', '31894']
- ['11875', '84904']
- ['133460', '139466']
- ['12624', '1379']
- ['116714', '138805']
- ['141207', '3242']
- ['164326', '5668']
- ['55087', '96949']
- ['121621', '151179']
- ['128369', '40146']
- ['11911', '28458']
- ['27700', '30468']
- ['117109', '120551']
- ['122761', '135712']
- ['116714', '140370']
- ['12589', '24658']
- ['139551', '99984']
- ['115595', '71683']
- ['161014', '165446']
- ['100115', '136636']
- ['122813', '59759']
- ['121131', '55958']
- ['54360', '99159']
- ['50273', '57164']
- ['65625', '73086']
- ['113908', '55958']
- ['114833', '36729']
- ['66452', '92654']
- ['32703', '89423']
- ['146362', '71465']
- ['31035', '67330']
- ['112066', '153213']
- ['23071', '98462']
- ['102998', '79925']
- ['112948', '34221']
- ['132425', '93933']
- ['159444', '8149']
- ['134156', '28599']
- ['84399', '87964']
- ['100115', '15086']
- ['93933', '95643']
- ['101366', '163653']
- ['64449', '77332']
- ['139059', '57199']
- ['27012', '50494']
- ['147924', '68140']
- ['59168', '66452']
- ['134739', '35263']
- ['102265', '89475']
- ['133628', '51544']
- ['139221', '89179']
- ['48144', '51932']
- ['138421', '143743']
- ['14688', '91575']
- ['107951', '35756']
- ['146052', '8197']
- ['130042', '136837']
- ['154892', '34787']
- ['134215', '166995']
- ['141747', '6683']
- ['103250', '108474']
- ['105024', '33427']
- ['135824', '46179']
- ['129966', '153213']
- ['136410', '59759']
- ['150349', '39407']
- ['133628', '61308']
- ['12624', '129223']
- ['116714', '130196']
- ['164326', '32861']
- ['115834', '62991']
- ['144012', '36729']
- ['67448', '76701']
- ['31219', '91575']
- ['12664', '148618']
- ['12624', '165499']
- ['147888', '52253']
- ['117109', '90056']
- ['31182', '83858']
- ['62673', '99824']
- ['142075', '94865']
- ['21274', '42884']
- ['121214', '153913']
- ['10266', '70552']
- ['149487', '54360']
- ['122665', '150004']
- ['83700', '91601']
- ['52167', '55958']
- ['113908', '57164']
- ['137473', '55169']
- ['105372', '79095']
- ['106891', '64002']
- ['134426', '96543']
- ['31196', '56103']
- ['117083', '143346']
- ['3162', '7196']
- ['28858', '48914']
- ['20003', '88801']
- ['50372', '69811']
- ['33361', '90403']
- ['133159', '33802']
- ['116509', '86748']
- ['146052', '20893']
- ['152150', '93933']
- ['143346', '60337']
- ['133628', '15702']
- ['114991', '33659']
- ['4148', '86282']
- ['107025', '35756']
- ['141207', '68275']
- ['106137', '66452']
- ['141207', '90437']
- ['62447', '72696']
- ['100115', '15917']
- ['144474', '46863']
- ['57164', '78191']
- ['127966', '92508']
- ['133628', '42315']
- ['116158', '88597']
- ['112971', '45422']
- ['133628', '42173']
- ['136382', '158221']
- ['141207', '15157']
- ['100115', '110525']
- ['9480', '98462']
- ['1336', '164326']
- ['21565', '55087']
- ['143743', '86297']
- ['109556', '139548']
- ['153213', '55120']
- ['11187', '93933']
- ['1147', '143346']
- ['12472', '93933']
- ['6229', '76339']
- ['102265', '126983']
- ['50496', '65227']
- ['63543', '93933']
- ['83916', '97323']
- ['26507', '50031']
- ['33902', '98856']
- ['139551', '149906']
- ['113817', '71465']
- ['48159', '6229']
- ['139059', '41202']
- ['115170', '163653']
- ['46344', '681']
- ['119534', '12624']
- ['30012', '8149']
- ['12624', '30119']
- ['35419', '93933']
- ['57164', '78921']
- ['154756', '55135']
- ['155757', '93933']
- ['62991', '84263']
- ['143346', '160858']
- ['119454', '74924']
- ['13734', '98462']
- ['146052', '84368']
- ['102627', '12624']
- ['12693', '90472']
- ['111504', '93933']
- ['122109', '2117']
- ['35263', '35360']
- ['34002', '90032']
- ['153213', '158197']
- ['127279', '8149']
- ['11672', '59759']
- ['94064', '96543']
- ['155322', '29886']
- ['118745', '135824']
- ['153136', '59397']
- ['134022', '143346']
- ['119551', '19696']
- ['161014', '86857']
- ['61486', '91575']
- ['114726', '90403']
- ['152081', '96973']
- ['144816', '55958']
- ['117051', '97604']
- ['26743', '681']
- ['113974', '60193']
- ['123820', '128454']
- ['135834', '1814']
- ['115333', '63189']
- ['5999', '96543']
- ['33952', '86410']
- ['57164', '65178']
- ['92508', '96558']
- ['29179', '29354']
- ['161115', '35889']
- ['74727', '95035']
- ['31206', '45125']
- ['151562', '164328']
- ['144474', '156167']
- ['30496', '40764']
- ['164326', '20889']
- ['151486', '8149']
- ['100272', '135436']
- ['110541', '91601']
- ['31102', '32196']
- ['135805', '92554']
- ['166995', '8117']
- ['112455', '139551']
- ['117109', '40313']
- ['130509', '137079']
- ['120590', '161014']
- ['82973', '92540']
- ['134589', '92538']
- ['19315', '32703']
- ['151900', '16486']
- ['141810', '166063']
- ['166063', '21899']
- ['36989', '38886']
- ['118887', '71533']
- ['110238', '93933']
- ['117109', '163750']
- ['106732', '32703']
- ['2579', '35889']
- ['117670', '12873']
- ['152651', '164326']
- ['17596', '96679']
- ['12624', '61220']
- ['110060', '33894']
- ['104142', '71465']
- ['65082', '71465']
- ['114928', '31849']
- ['151151', '80883']
- ['141207', '44463']
- ['12624', '5595']
- ['52073', '93933']
- ['122665', '166466']
- ['133628', '158617']
- ['167068', '681']
- ['10304', '126762']
- ['11027', '133628']
- ['25176', '42475']
- ['124931', '92508']
- ['164328', '6703']
- ['35263', '40664']
- ['138202', '157365']
- ['149899', '164326']
- ['137957', '28858']
- ['143346', '96828']
- ['164620', '93933']
- ['163100', '166995']
- ['120097', '43540']
- ['59408', '69637']
- ['12624', '2107']
- ['126119', '57164']
- ['131434', '55958']
- ['12624', '135938']
- ['123240', '163990']
- ['165927', '2370']
- ['133628', '53562']
- ['10650', '44009']
- ['100212', '102324']
- ['12624', '20913']
- ['116714', '88260']
- ['6096', '88100']
- ['132840', '133628']
- ['36374', '91575']
- ['6589', '66452']
- ['32381', '88317']
- ['28858', '80738']
- ['141932', '88124']
- ['144474', '98433']
- ['58747', '681']
- ['38276', '59759']
- ['65851', '83533']
- ['133628', '156258']
- ['125113', '54360']
- ['121043', '7206']
- ['55958', '83610']
- ['23710', '91601']
  
 